### ISSUE TITLE
ascii video example error

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/ofxOfelia#13]
when i try to run the ascii video example with the newest version (2.3.1) i get this error message:
: ofPixels: format doesn't support channels
: returning color not supported yet for UNKOWN format

**Comment by cuinjune** [comment]
@Jonathhhan Hi, could you tell me which Operating System you are using? (e.g. `Windows 10`)

**Comment by Jonathhhan** [comment]
hi. yes, it is windows 10.

**Comment by cuinjune** [comment]
@Jonathhhan So do you not see anything on the graphics window when you run the ascii video example?

**Comment by Jonathhhan** [comment]
thanks, the lower code does work.
