### ISSUE TITLE
Ofelia on windows

### ISSUE THREAD

**Issue by b2renger** [cuinjune/ofxOfelia#4]
Hello, and thanks for this awesome project !

I manage to install ofelia through deken on mac os, but it doesn't show up on windows (win 10, and pd 0.49.1). It's actually a bit weird because I see the windows versions in the list of proposed external when I do a search on mac.

I tried to install it manually on windows eg copying files in "mypath/pd/externals" adding the path to startup but I couldn't manage to get the lib to work on windows.

I would be willing to test stuff out if necessary don't hesitate to ping me .

**Comment by cuinjune** [comment]
Hi @b2renger 

Which version of ofelia did you download on WIndows?
You should download ofelia 1.0.8 since ofelia 2.0 is not ready yet.
Please try any example patch inside ofelia/examples folder to see if it works.

**Comment by b2renger** [comment]
@cuinjune , yes you are right I was testing 2.0. Closing then. Thanks !
