### ISSUE TITLE
pd.Array's setTable() function (Windows)

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/ofxOfelia#6]
Hi Cuinjune, 
the pd.Array's setTable() function for setting Pure Data tables seems to only resize and not to set the table on Windows OS.

**Comment by cuinjune** [comment]
@Jonathhhan This is now fixed in the new version v2.0.4.
Please check out [CHANGES.txt](https://github.com/cuinjune/ofxOfelia/blob/master/CHANGES.txt) to find out what has changed.
Thank you for your contribution to Ofelia.
