### ISSUE TITLE
Running on crouton ubuntu 16.04

### ISSUE THREAD

**Issue by miker2049** [cuinjune/ofxOfelia#8]
Hi, 
I am having trouble getting ofelia to work on my chromebook with pure data 0.49.  (ubuntu xenial)

Installed with deken, and ran the ubuntu/install_dependencies.sh 

doing `ldd ofelia.pd_linux` 
outputs
```
./ofelia.pd_linux: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./ofelia.pd_linux)
./ofelia.pd_linux: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./ofelia.pd_linux)
./ofelia.pd_linux: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by ./ofelia.pd_linux)
``` 

I understand that these are some big system libraries that are not updated enough in my version of ubuntu... is there anything I can do about this? other than try and upgrade by ubuntu?  Is it possible to try and compile it myself?  If so, where are the source files to be made?

Thanks!

**Comment by cuinjune** [comment]
Hi, @miker2049 

The latest version of ofelia was built in Ubuntu 18.04.
I think you should try to compile ofelia yourself.

1. First, you need to download [openFrameworks v0.10.0 for Linux 64bit](https://openframeworks.cc/versions/v0.10.0/).

2. Follow [the installation guide](https://openframeworks.cc/setup/linux-install/) to install openFrameworks.

3. Download [ofxOfelia_Linux64.zip](https://github.com/cuinjune/ofxOfelia/releases/download/v2.0.4/ofxOfelia_Linux64.zip).

4. Unzip it, rename the folder to `ofxOfelia` and place it inside `OF/addons` directory.

5. Move `ofxOfelia/libs/ofxLua` folder to `OF/addons`

6. Open the Terminal cd to `ofxOfelia/scripts/Linux64` and run `./updateOF.sh`.

7. cd to `ofxOfelia/Linux64External` and run `make` to compile.

8. Find the generated `ofelia.pd_linux` file inside `ofxOfelia/Linux64External/bin` and replace it with the one you have inside `ofelia` directory.

Let me know if you have any questions.

**Comment by miker2049** [comment]
With a little fiddling, this worked just fine for me! 
Thanks for this.
I might recommend putting these instructions in the README.md in case other people want to compile ofelia themselves. 

Either way, 
cheers
