### ISSUE TITLE
ofelia on arch linux - rolling edge is edgy

### ISSUE THREAD

**Issue by 5shekel** [cuinjune/ofxOfelia#9]
following the install instructions, and after running 
`ofelia/scripts/arch_linux/install_dependencies.sh`
when i try to initiate [ofelia] i get the following error
`/home/user/pd/externals/ofelia/ofelia.pd_linux: libGLEW.so.2.0: cannot open shared object file: No such file or directory`

mm... i see 
i had to install the specific 2.0 version of glew,  they coexist. 
`yay glew2.0`
fixed that one
```
$ ldconfig -p | grep libGLEW
	libGLEW.so.2.1 (libc6,x86-64) => /usr/lib/libGLEW.so.2.1
	libGLEW.so.2.0 (libc6,x86-64) => /usr/lib/libGLEW.so.2.0
	libGLEW.so (libc6,x86-64) => /usr/lib/libGLEW.so
```
i'm running mesa driver on an x230 laptop

**Comment by 5shekel** [comment]
but... libboost is also suffering from arch bleeding edginess. this time there is no option, have to roll-back?
`
/home/user/pd/externals/ofelia/ofelia.pd_linux: libboost_filesystem.so.1.65.1: cannot open shared object file: No such file or directory
`
```
$ ldconfig -p | grep libboost_filesystem
	libboost_filesystem.so.1.69.0 (libc6,x86-64) => /usr/lib/libboost_filesystem.so.1.69.0
	libboost_filesystem.so (libc6,x86-64) => /usr/lib/libboost_filesystem.so
```

**Comment by cuinjune** [comment]
Hi @5shekel 
Can you try compiling ofelia external yourself by following [this instruction](https://github.com/cuinjune/ofxOfelia/issues/8#issuecomment-463173798)?
Make sure you select the correct version for your system.

**Comment by 5shekel** [comment]
yes! i was looking for such build instructions. didn't look hard enough. 
the build instructions errored out with an [ofxLua issue](https://github.com/danomatika/ofxLua/issues/53), easy fix, had to install the `swig` and `luajit` packages from arch repo

seconded to add this to the readme.

**Comment by mxa** [comment]
Same problem on ubuntu 19.04, but there is no more libglew2.0 in the repositories, only libglew2.1
