### ISSUE TITLE
Feature request: Send values to PD from a Lua script.

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/ofxOfelia#93]
Currently it is only possible, if an Ofelia object is called with a PD message / bang / number etc.. It would be really nice, if this is possible from within a Lua script, too. Maybe send the variable to a PD `[receive]` object?

**Comment by cuinjune** [comment]
Isn't that already possible? Do you want to have a look at the`ofelia/examples/pd/misc` example? You will find examples to send and receive data in an Ofelia object.

**Comment by Jonathhhan** [comment]
Actually I tried to adapt this example: https://github.com/cuinjune/Ofelia/tree/master/ofelia/examples/pd/metro
But it only seems to return to the outlet, if at least one message etc. is send to the inlet of the `Ofelia` object.
I would like, for example, to return a bang at `ofSetup` (or sending values from the OF GUI to PD).
(I can make a minimal example to show the idea)

Will check the `ofelia/examples/pd/misc` example soon.

**Comment by Jonathhhan** [comment]
> Isn't that already possible? Do you want to have a look at theofelia/examples/pd/misc example? You will find examples to send and receive data in an Ofelia object.

Yes, it is possible. I already forgot. Nice. `ofSend()` is what I was searching for.
