### ISSUE TITLE
For what is ofxMidi (in ofxOfelia) needed?

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/ofxOfelia#94]
Hi.
I wonder what is the purpose of ofxMidi in ofxOfelia. Of course it would be possible to write / generate Lua bindings for it, but it seems that callbacks / listeners are difficult in Lua (as far as I know). Is ofxMidi currently without functionality in OfxOfelia?

**Comment by cuinjune** [comment]
I think the purpose of it is to allow using MIDI in standalone applications (not the external).

**Comment by Jonathhhan** [comment]
Ah yes, makes sense. I was wondering, because I never used it. Thanks.
