### ISSUE TITLE
GLFW Window 

### ISSUE THREAD

**Issue by Jonathhhan** [cuinjune/ofxOfelia#95]
Is possible to use GLFW with Ofelia? That would be really nice for ImGui viewport support (already included it for the swig bindings). Then it would be possible, to use the ImGui windows without the OF window: https://forum.openframeworks.cc/t/ofximgui-is-it-possible-to-hide-the-main-window-and-show-2-ofximgui-windows/42848?u=jona

**Comment by cuinjune** [comment]
I think it uses `ofWindowSettings` which might internally use `ofGLFWWindowSettings` on Desktop. I'm not sure about this though. Maybe you can try including the `ofGLFWWindowSettings` in https://github.com/cuinjune/Ofelia/blob/master/libs/ofxLua/swig/openFrameworks/openFrameworks/app.i and regenerate SWIG bindings, or try replacing `ofWindowSettings` to `ofGLFWWindowSettings` from https://github.com/cuinjune/Ofelia/blob/master/libs/ofxLua/src/bindings/desktop/ofBindings.cpp and rebuild the external. I'm not sure if this will work though. You might also need to update https://github.com/cuinjune/Ofelia/blob/master/ofelia/abs/ofWindow.lua to properly create and use GLFW window.

**Comment by cuinjune** [comment]
Also, just for your reference, Ofelia v1.0 used `ofGLFWWindowSettings` to create a window: https://github.com/cuinjune/Ofelia/blob/v1.0.0/macOSExternal/src/ofeliaWindow.cpp#L1120C5-L1120C25

**Comment by Jonathhhan** [comment]
@cuinjune thank you.

**Comment by Jonathhhan** [comment]
@cuinjune I solved it. I needed to make some changes here: https://github.com/danomatika/swig-openframeworks/compare/master...Jonathhhan:swig-openframeworks:OF-master and also here: https://github.com/Jonathhhan/ofxOfeliaExtended/commit/6ea9981002c0419617fbc5fe964f237f07614c28
This way you can have one ore several ImGui windows without an OF window (which could be nice for a PD GUI).
![Screenshot 2024-05-13 173351](https://github.com/cuinjune/Ofelia/assets/41275844/890f141b-a9fa-4767-a810-5a1e6a3e0abb)
